symfony/src/Entity/Album.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Album
 *
 * @ORM\Table(name="Album", indexes={@ORM\Index(name="IDX_F8594147E1990660", columns={"Code_Genre"}), @ORM\Index(name="IDX_F8594147EA8CE117", columns={"Code_Editeur"})})
 * @ORM\Entity(repositoryClass="App\Repository\AlbumRepository")
 */
class Album
{
    /**
     * @var int
     *
     * @ORM\Column(name="Code_Album", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $codeAlbum;

    /**
     * @var string
     *
     * @ORM\Column(name="Titre_Album", type="string", length=400, nullable=false)
     */
    private $titreAlbum;

    /**
     * @var int|null
     *
     * @ORM\Column(name="Annee_Album", type="integer", nullable=true)
     */
    private $anneeAlbum;

    /**
     * @var binary|null
     *
     * @ORM\Column(name="Pochette", type="binary", nullable=true)
     */
    private $pochette;

    /**
     * @var string|null
     *
     * @ORM\Column(name="ASIN", type="string", length=20, nullable=true)
     */
    private $asin;

    /**
     * @var \Genre
     *
     * @ORM\ManyToOne(targetEntity="Genre")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="Code_Genre", referencedColumnName="Code_Genre")
     * })
     */
    private $codeGenre;

    /**
     * @var \Editeur
     *
     * @ORM\ManyToOne(targetEntity="Editeur")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="Code_Editeur", referencedColumnName="Code_Editeur")
     * })
     */
    private $codeEditeur;

    public function getCodeAlbum(): ?int
    {
        return $this->codeAlbum;
    }

    public function getTitreAlbum(): ?string
    {
        return $this->titreAlbum;
    }

    public function setTitreAlbum(string $titreAlbum): self
    {
        $this->titreAlbum = $titreAlbum;

        return $this;
    }

    public function getAnneeAlbum(): ?int
    {
        return $this->anneeAlbum;
    }

    public function setAnneeAlbum(?int $anneeAlbum): self
    {
        $this->anneeAlbum = $anneeAlbum;

        return $this;
    }

    public function getPochette()
    {
        return $this->pochette;
    }

    public function setPochette($pochette): self
    {
        $this->pochette = $pochette;

        return $this;
    }

    public function getAsin(): ?string
    {
        return $this->asin;
    }

    public function setAsin(?string $asin): self
    {
        $this->asin = $asin;

        return $this;
    }

    public function getCodeGenre(): ?Genre
    {
        return $this->codeGenre;
    }

    public function setCodeGenre(?Genre $codeGenre): self
    {
        $this->codeGenre = $codeGenre;

        return $this;
    }

    public function getCodeEditeur(): ?Editeur
    {
        return $this->codeEditeur;
    }

    public function setCodeEditeur(?Editeur $codeEditeur): self
    {
        $this->codeEditeur = $codeEditeur;

        return $this;
    }
    public function getBase64Pochette(): ?string
    {
        $string = stream_get_contents($this->pochette);
        return (base64_encode($string));
    }

}

symfony/src/Entity/Enregistrement.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Enregistrement
 *
 * @ORM\Table(name="Enregistrement")
 * @ORM\Entity
 */
class Enregistrement
{
    /**
     * @var int
     *
     * @ORM\Column(name="Code_Morceau", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $codeMorceau;

    /**
     * @var string
     *
     * @ORM\Column(name="Titre", type="string", length=0, nullable=false)
     */
    private $titre;

    /**
     * @var int
     *
     * @ORM\Column(name="Code_Composition", type="integer", nullable=false)
     */
    private $codeComposition;

    /**
     * @var string
     *
     * @ORM\Column(name="Nom_de_Fichier", type="string", length=0, nullable=false)
     */
    private $nomDeFichier;

    /**
     * @var string|null
     *
     * @ORM\Column(name="Duree", type="string", length=10, nullable=true, options={"fixed"=true})
     */
    private $duree;

    /**
     * @var int|null
     *
     * @ORM\Column(name="Duree_Seconde", type="integer", nullable=true)
     */
    private $dureeSeconde;

    /**
     * @var int|null
     *
     * @ORM\Column(name="Prix", type="integer", nullable=true)
     */
    private $prix;

    /**
     * @var binary|null
     *
     * @ORM\Column(name="Extrait", type="binary", nullable=true)
     */
    private $extrait;

    public function getCodeMorceau(): ?int
    {
        return $this->codeMorceau;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getCodeComposition(): ?int
    {
        return $this->codeComposition;
    }

    public function setCodeComposition(int $codeComposition): self
    {
        $this->codeComposition = $codeComposition;

        return $this;
    }

    public function getNomDeFichier(): ?string
    {
        return $this->nomDeFichier;
    }

    public function setNomDeFichier(string $nomDeFichier): self
    {
        $this->nomDeFichier = $nomDeFichier;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(?string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDureeSeconde(): ?int
    {
        return $this->dureeSeconde;
    }

    public function setDureeSeconde(?int $dureeSeconde): self
    {
        $this->dureeSeconde = $dureeSeconde;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getExtrait()
    {
        return $this->extrait;
    }

    public function setExtrait($extrait): self
    {
        $this->extrait = $extrait;

        return $this;
    }

    public function getBase64Extrait(): ?string
    {
        if ($this->extrait != null){
            $string = stream_get_contents($this->extrait);
            return (base64_encode($string));
        }
        return "Extrait indisponible";
    }

}

symfony/src/Controller/CatalogueController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Entity\Editeur;
use App\Entity\Genre;
use App\Entity\Musicien;
use App\Entity\Oeuvre;
use App\Repository\AlbumRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;


/**
 * @Route("/catalogue")
 */
class CatalogueController extends AbstractController
{
    /**
     * @Route("/", name="albums_index")
     * @param Request $request
     * @return Response
     */
    public function index(Request $request):Response
    {
        $search = NULL;
        $formulaire = $this->createFormBuilder()
            ->add('search', SearchType::class, array('constraints' => new Length(array('min' => 3)), 'attr' => array('placeholder' => 'Rechercher un produit')))
            ->add('send', SubmitType::class, array('label' => 'Rechercher'))
            ->getForm();

        $formulaire->handleRequest($request);

        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $search = $request->get('form')['search'];
            $albums = $this->getDoctrine()
                ->getRepository(Album::class)
                ->findAlbumsResearch($search);

        } else {
            $albums = $this->getDoctrine()
                ->getRepository(Album::class)
                ->findAll();
        }

        return $this->render('catalogue/index.html.twig', [
            'albums' => $albums,
            'formulaire' => $formulaire -> createView()
        ]);
    }
    /**
     * @Route("/{codeAlbum}", name="album_show", methods={"GET"})
     */
    public function show(Album $album): Response
    {
        $editeur = $this->getDoctrine()
            ->getRepository(Editeur::class)
            ->find($album->getCodeEditeur());
        $genre = $this->getDoctrine()
            ->getRepository(Genre::class)
            ->find($album->getCodeGenre());
        $enregistrements=$this->getDoctrine()
            ->getRepository(Album::class)
            ->findEnregistrements($album);
        return $this->render('catalogue/album.html.twig',['album'=>$album,'editeur'=>$editeur,
            'genre'=>$genre, 'enregistrements'=>$enregistrements]);


    }

}

symfony/templates/catalogue/album.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche Album{% endblock %}

{% block body %}
    <br>
    <h1> {{ album.titreAlbum }} </h1>


    <img src="data:image/png;base64,{{ album.base64Pochette }}" alt=''>

    <br>

    <table class="table">
        <tbody>
        <tr>
            <th>Editeur</th>
        <td> {{ editeur.nomEditeur }}</td>
        </tr>
        <tr>
            <th>Genre</th>
            <td>{{ genre.libelleAbrege}}</td>
        </tr>
        <tr>
            <th>Année de sortie</th>
            <td>{{ album.anneeAlbum }}</td>
        </tr>
        <tr>
            <th>Shopper</th>
            <td>
                <a href="{{ path('ajout-panier-album',{'codeAlbum':album.codeAlbum}) }}"><img src="https://img.icons8.com/windows/50/000000/add-shopping-cart.png" alt=""></a>
                <a href="http://www.amazon.com/dp/{{ album.asin }}"><img height="32" width="32" src="https://pngimg.com/uploads/amazon/amazon_PNG27.png"></a>
            </td>
        </tr>
        </tbody>
        {% for enregistrement in enregistrements %}
            <tr>
                <th>Titre</th>
                <td>{{ enregistrement.titre }}</td>
                <th>Prix</th>
                <td>{{ enregistrement.prix }} €</td>
                <td><a href="{{ path('ajout-panier-enregistrement',{'codeEnregistrement': enregistrement.codeMorceau}) }}"><img src="https://img.icons8.com/windows/50/000000/add-shopping-cart.png" alt=""></a></td>
                <th>Extrait</th>
                <td><audio
                            controls
                            src="data:audio/mp3;base64,{{ enregistrement.base64Extrait }}" >
                        Votre navigateur ne supporte pas l'élément
                        <code>audio</code>.
                    </audio>
                </td>
            </tr>
        {% endfor %}
    </table>

    <a href="{{ path('albums_index') }}">Retour</a>

{% endblock %}

symfony/templates/catalogue/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue{% endblock %}

{% block body %}
    <h1 style="text-align: center">Oeuvres disponibles</h1>

    {% block search %}
        {% if formulaire is defined %}
            <div>
                {{ form_start(formulaire, { 'attr': {'class': 'navbar-form navbar-left'} }) }}
                <div>
                    <div>
                        {{ form_widget(formulaire.search, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                    <div>
                        {{ form_widget(formulaire.send, { 'attr': {'class': 'btn btn-default'} } ) }}
                    </div>
                </div>
                {{ form_rest(formulaire) }}
                {{ form_end(formulaire) }}
            </div>
        {% endif %}
    {% endblock search %}

    <table class="table">
        {% set cpt = 0 %}
        <tbody>
        <tr>
            {% for album in albums%}

            <td style="text-align: center">
                <div>{{ album.titreAlbum }}</div>

                <div><a href="{{ path('album_show', {'codeAlbum': album.codeAlbum}) }}">
                        <img src="data:image/png;base64,{{ album.getBase64Pochette}}" height="200" width="250" alt=''>
                    </a></div>
            </td>

            {% set cpt = cpt+1%}

            {%if cpt%5==0%}

        </tr><tr>

            {% endif %}

            {% else %}
        {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}