symfony/src/Entity/Musicien.php
<?php

namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Musicien
 *
 * @ORM\Table(name="Musicien", indexes={@ORM\Index(name="IDX_AC6BE67520B77BF2", columns={"Code_Pays"}), @ORM\Index(name="IDX_AC6BE675E1990660", columns={"Code_Genre"}), @ORM\Index(name="IDX_AC6BE675D389A975", columns={"Code_Instrument"})})
 * @ORM\Entity(repositoryClass="App\Repository\MusicienRepository")
 */
class Musicien
{
    /**
     * @var int
     *
     * @ORM\Column(name="Code_Musicien", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $codeMusicien;

    /**
     * @var string
     *
     * @ORM\Column(name="Nom_Musicien", type="string", length=200, nullable=false)
     */
    private $nomMusicien;

    /**
     * @var string|null
     *
     * @ORM\Column(name="Prenom_Musicien", type="string", length=50, nullable=true)
     */
    private $prenomMusicien;

    /**
     * @var int|null
     *
     * @ORM\Column(name="Annee_Naissance", type="integer", nullable=true)
     */
    private $anneeNaissance;

    /**
     * @var int|null
     *
     * @ORM\Column(name="Annee_Mort", type="integer", nullable=true)
     */
    private $anneeMort;

    /**
     * @var binary|null
     *
     * @ORM\Column(name="Photo", type="binary", nullable=true)
     */
    private $photo;

    /**
     * @var \Pays
     *
     * @ORM\ManyToOne(targetEntity="Pays")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="Code_Pays", referencedColumnName="Code_Pays")
     * })
     */
    private $codePays;

    /**
     * @var \Genre
     *
     * @ORM\ManyToOne(targetEntity="Genre")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="Code_Genre", referencedColumnName="Code_Genre")
     * })
     */
    private $codeGenre;

    /**
     * @var \Instrument
     *
     * @ORM\ManyToOne(targetEntity="Instrument")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="Code_Instrument", referencedColumnName="Code_Instrument")
     * })
     */
    private $codeInstrument;

    /**
     * Many Users have Many Groups.
     * @ORM\ManyToMany(targetEntity="Oeuvre")
     * @ORM\JoinTable(name="Composer",
     *      joinColumns={@ORM\JoinColumn(name="Code_Musicien", referencedColumnName="Code_Musicien")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="Code_Oeuvre", referencedColumnName="Code_Oeuvre")}
     *      )
     */
    private $oeuvres;

    public function getCodeMusicien(): ?int
    {
        return $this->codeMusicien;
    }

    public function getOeuvres()
    {
        return $this->oeuvres;
    }

    public function getNomMusicien(): ?string
    {
        return $this->nomMusicien;
    }

    public function setNomMusicien(string $nomMusicien): self
    {
        $this->nomMusicien = $nomMusicien;

        return $this;
    }

    public function getPrenomMusicien(): ?string
    {
        return $this->prenomMusicien;
    }

    public function setPrenomMusicien(?string $prenomMusicien): self
    {
        $this->prenomMusicien = $prenomMusicien;

        return $this;
    }

    public function getAnneeNaissance(): ?int
    {
        return $this->anneeNaissance;
    }

    public function setAnneeNaissance(?int $anneeNaissance): self
    {
        $this->anneeNaissance = $anneeNaissance;

        return $this;
    }

    public function getAnneeMort(): ?int
    {
        return $this->anneeMort;
    }

    public function setAnneeMort(?int $anneeMort): self
    {
        $this->anneeMort = $anneeMort;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto($photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCodePays(): ?Pays
    {
        return $this->codePays;
    }

    public function setCodePays(?Pays $codePays): self
    {
        $this->codePays = $codePays;

        return $this;
    }

    public function getCodeGenre(): ?Genre
    {
        return $this->codeGenre;
    }

    public function setCodeGenre(?Genre $codeGenre): self
    {
        $this->codeGenre = $codeGenre;

        return $this;
    }

    public function getCodeInstrument(): ?Instrument
    {
        return $this->codeInstrument;
    }

    public function setCodeInstrument(?Instrument $codeInstrument): self
    {
        $this->codeInstrument = $codeInstrument;

        return $this;
    }

    public function getBase64Photo(): ?string 
    {
        if ($this->photo != null){
            $string = stream_get_contents($this->photo);
            return (base64_encode($string));
        }
       return "Photo indisponible";
    }
}

symfony/src/Controller/MusicienController.php
<?php

namespace App\Controller;

use App\Entity\Composer;
use App\Entity\Musicien;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;


/**
 * @Route("/musicien")
 */
class MusicienController extends AbstractController
{
    /**
     * @Route("/", name="musicien_index")
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $search = NULL;
        $formulaire = $this->createFormBuilder()
            ->add('search', SearchType::class, array('constraints' => new Length(array('min' => 3)), 'attr' => array('placeholder' => 'Rechercher un musicien   ')))
            ->add('send', SubmitType::class, array('label' => 'Rechercher'))
            ->getForm();

        $formulaire->handleRequest($request);

        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $search = $request->get('form')['search'];
            $musiciens = $this->getDoctrine()
                ->getRepository(Musicien::class)
                ->findMusicienResearch($search);

        } else {
            $musiciens = $this->getDoctrine()
                ->getRepository(Musicien::class)
                ->findAll();
        }

        return $this->render('musicien/index.html.twig', ['musiciens' => $musiciens,
            'formulaire' => $formulaire->createView()]);
    }

    /**
     * @Route("/{codeMusicien}", name="musicien_show", methods={"GET"})
     * @param Musicien $musicien
     * @return Response
     */
    public function show( Musicien $musicien): Response
    {
        $albums = $this->getDoctrine()
            ->getRepository(Musicien::class)
            ->findAlbumsByMusicien($musicien);

        return $this->render('musicien/show.html.twig',
            ['musicien' => $musicien,
                'oeuvres' => $musicien->getOeuvres(),
                'albums' => $albums
            ]);
    }


}

symfony/templates/musicien/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Compositeurs{% endblock %}

{% block body %}
    <br>
    <h1 style="text-align: center">Compositeurs</h1>

    {% block search %}
        {% if formulaire is defined %}
            <div>
                {{ form_start(formulaire, { 'attr': {'class': 'navbar-form navbar-right'} }) }}
                <div >
                    <div >
                        {{ form_widget(formulaire.search, { 'attr': {'class': 'form-control'} }) }}
                    </div>
                    <div >
                        {{ form_widget(formulaire.send, { 'attr': {'class': 'btn btn-default'} } ) }}
                    </div>
                </div>
                {{ form_rest(formulaire) }}
                {{ form_end(formulaire) }}
            </div>
        {% endif %}
    {% endblock search %}

    <table class="table">
        {% set cpt = 0 %}
        <tbody>
        <tr>
        {% for musicien in musiciens %}

            <td style="text-align: center">

            <div>{{ musicien.prenomMusicien }} {{ musicien.nomMusicien }} </div>

             <img src="data:image/png;base64,{{ musicien.base64Photo }}" height="200" width="250" alt=''>
                <br>
                <div>
                <a href="{{ path('musicien_show', {'codeMusicien': musicien.codeMusicien}) }}">Détails</a>
                </div>
            </td>

        {% set cpt = cpt+1%}

            {%if cpt%5==0%}

            </tr><tr>

            {% endif %}

        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tr>
        </tbody>
    </table>

    <a href="{{ path('musicien_index') }}">Revenir à la liste</a>
{% endblock %}

symfony/templates/musicien/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Musicien{% endblock %}

{% block body %}
    <br>
    <h1> {{ musicien.nomMusicien }} </h1>

    <img src="data:image/png;base64,{{ musicien.base64Photo }}" alt=''>

    <br>

    <table class="table">
        <tbody>
        <tr>
            <th>Nom</th>
            <td>{{ musicien.nomMusicien }}</td>
        </tr>
        <tr>
            <th>Prénom</th>
            <td>{{ musicien.prenomMusicien }}</td>
        </tr>
        <tr>
            <th>Date de naissance</th>
            <td>{{ musicien.anneeNaissance }}</td>
        </tr>
        <tr>
            <th>Date de mort</th>
            <td>{{ musicien.anneeMort }}</td>
        </tr>
        <tr>
            <th>Liste de ses oeuvres et albums</th>
        <tbody>
        <tr>
            <td>
        {% for oeuvre in oeuvres %}

            {{ oeuvre.titreOeuvre }}

        {% endfor %}
            </td>
            <td>
                {% for album in albums %}
                <a href="{{ path('album_show', {'codeAlbum': album.codeAlbum}) }}">
                    <img src="data:image/png;base64,{{ album.getBase64Pochette}}" height="200" width="250" alt=''>
                </a>
                {% endfor %}
            </td>
        </tr>
        </tbody>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('musicien_index') }}">Revenir à la liste</a>

{% endblock %}